### ISSUE TITLE
Setup dependabot

### ISSUE THREAD

**Issue by cjmartian** [ous8292/rx-goods-site#12]
We should setup [dependabot ](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates) for better dependency management.

**Comment by psteyer** [comment]
Does this just keep all the dependencies up to date automatically?

**Comment by cjmartian** [comment]
Does quite a bit actually, will look at your dependencies and check if there are security issues with them as well, but yeah it basically keeps dependencies up to date for you.

**Comment by psteyer** [comment]
Oh wow! Yea that would be awesome to implement. I'll start reading up about it and checking it out.

**Comment by cjmartian** [comment]
Let me know if you need any help with it!
